ads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = 'ads'

urlpatterns = [

    path('', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create', views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update', views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete', views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),

    path('ad/<int:pk>/comment/create', views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('ad/comment/<int:pk>', views.CommentDetailView.as_view(), name='ad_comment_detail'),
    path('ad/comment/<int:pk>/update', views.CommentUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_comment_update'),
    path('ad/comment/<int:pk>/delete', views.CommentDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_comment_delete'),

    path('ad/<int:pk>/favorite', views.FavoriteAddView.as_view(), name='ad_favorite'),
    path('ad/<int:pk>/unfavorite', views.FavoriteDeleteView.as_view(), name='ad_unfavorite'),

]

autos/urls.py
from django.urls import path
from . import views

app_name = 'autos'
urlpatterns = [

    path("", views.MainView.as_view(), name="all"),

    #path('main/', views.AutosListView.as_view(), name='autos-list'),
    path('main/create/', views.AutosCreateView.as_view(), name='autos-create'),
    path('main/<int:pk>/update/', views.AutosUpdateView.as_view(), name='autos-update'),
    path('main/<int:pk>/delete/', views.AutosDeleteView.as_view(), name='autos-delete'),

    path('lookup/', views.MakeListView.as_view(), name='make-list'),
    path('lookup/create/', views.MakeCreateView.as_view(), name='make-create'),
    path('lookup/<int:pk>/update/', views.MakeUpdateView.as_view(), name='make-update'),
    path('lookup/<int:pk>/delete/', views.MakeDeleteView.as_view(), name='make-delete'),

]

mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('home.urls')),  # Change to ads.urls
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep

    path('ads/', include('ads.urls')),
    path('cats/', include('cats.urls')),
    path('autos/', include('autos.urls')),

]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0, path('accounts/login/', \
        auth_views.LoginView.as_view(template_name=social_login)))
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/4.2/ref/urls/#include

autos/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MinLengthValidator

# Create your models here.

class Make(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False,
        help_text='Enter a make (e.g. Honda)',
        validators=[MinLengthValidator(2, "Make must be greater than 1 character")])
    def get_absolute_url(self):
        return reverse('make-list')
    def __str__(self):
        return str(self.name)

class Autos(models.Model):
    nickname = models.CharField(max_length=50, default="", null=False, blank=False,
        validators=[MinLengthValidator(2, "Nickname must be greater than 1 character")])
    make = models.ForeignKey('Make', on_delete=models.CASCADE, null=False)
    mileage = models.PositiveIntegerField(default=0, null=True, blank=True)
    comments = models.CharField(max_length=300, default="", null=True, blank=True)
    def get_absolute_url(self):
        return reverse('auto-list')
    def __str__(self):
        return self.nickname

autos/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
#from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
#from .forms import MakeForm
from .models import Autos, Make

# Create your views here.

class MainView(LoginRequiredMixin, View):
    def get(self, request):
        mc = Make.objects.count()
        al = Autos.objects.all()
        ctx = {'make_count': mc, 'auto_list': al}
        return render(request, 'autos/autos_list.html', ctx)

### Autos
class AutosListView(LoginRequiredMixin, ListView):
    model = Autos
    context_object_name = 'auto'
    template_name = 'autos/autos_list.html'

class AutosCreateView(LoginRequiredMixin, CreateView):
    model = Autos
    fields = '__all__'
    success_url = reverse_lazy('autos:all')
    template_name = 'autos/autos_form.html'

class AutosUpdateView(LoginRequiredMixin, UpdateView):
    model = Autos
    fields = '__all__'
    success_url = reverse_lazy('autos:all')
    template_name = 'autos/autos_form.html'

class AutosDeleteView(LoginRequiredMixin, DeleteView):
    model = Autos
    fields = '__all__'
    success_url = reverse_lazy('autos:all')
    template_name = 'autos/autos_confirm_delete.html'


### Make
class MakeListView(LoginRequiredMixin, View):
    def get(self, request):
        ml = Make.objects.all()
        ctx = {'make_list': ml}
        return render(request, 'autos/make_list.html', ctx)

# class MakeListView(LoginRequiredMixin, ListView):
#     model = Make
#     context_object_name = 'make'
#     template_name = 'autos/make_list.html'

class MakeCreateView(LoginRequiredMixin, CreateView):
    model = Make
    fields = '__all__'
    success_url = reverse_lazy('autos:make-list')
    template_name = 'autos/make_form.html'

class MakeUpdateView(LoginRequiredMixin, UpdateView):
    model = Make
    fields = '__all__'
    success_url = reverse_lazy('autos:make-list')
    template_name = 'autos/make_form.html'

class MakeDeleteView(LoginRequiredMixin, DeleteView):
    model = Make
    success_url = reverse_lazy('autos:make-list')
    template_name = 'autos/make_confirm_delete.html'

autos/templates/autos/autos_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Auto</h1>

<p>Are you sure you want to delete the Auto: {{ auto }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" onclick="window.location='{% url 'autos:all' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

autos/templates/autos/autos_form.html
{% extends "base_bootstrap.html" %}

{% block content %}

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'autos:all' %}' ; return false;" value="Cancel">
  </form>

{% endblock %}

autos/templates/autos/autos_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Auto List</h1>
  {% if auto_list %}
  <ul>
    {% for auto in auto_list %}
      <li>
          {{ auto.nickname }} ({{ auto.make }})
          (<a href="{% url 'autos:autos-update' auto.id %}">Update</a> |
          <a href="{% url 'autos:autos-delete' auto.id %}">Delete</a>) <br/>
          {{ auto.comments }} ({{ auto.mileage }} miles)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no Autos in the library.</p>
  {% endif %}
  <p>
    {% if make_count > 0 %}
      <a href="{% url 'autos:autos-create' %}">Add an auto</a>
    {% else %}
      Please add a Make before you add an Auto.
    {% endif %}
  </p>
  <p>
  <a href="{% url 'autos:make-list' %}">View makes</a> ({{ make_count }}) |
    <a href="{% url 'autos:make-create' %}">Add a make</a>
  </p>
{% endblock %}

autos/templates/autos/make_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Make</h1>

<p>Are you sure you want to delete the Make: {{ make }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" onclick="window.location='{% url 'autos:make-list' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

autos/templates/autos/make_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'autos:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

autos/templates/autos/make_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Make List</h1>
  {% if make_list %}
  <ul>
    {% for make in make_list %}
      <li>
          {{ make.name }}
         (<a href="{% url 'autos:make-update' make.id %}">Update</a> |
          <a href="{% url 'autos:make-delete' make.id %}">Delete</a>)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no Makes in the library.</p>
  {% endif %}
  <p><a href="{% url 'autos:make-create' %}">Add a make</a></p>
  <p><a href="{% url 'autos:make-list' %}">View makes</a></p>
  <p>
    <a href="{% url 'autos:all' %}">Back to autos</a>
  </p>
{% endblock %}